### PR TITLE
SOF-1182 Reenable no-duplicate-enum-values

### PR DESCRIPTION
**Pull request by LindvedKrvang**
Reenable no-duplicate-enum-value. Refactor away from duplicate enum value

### CODE REVIEW

**Review by RasmusAlbrektsen — APPROVED** [review]
Compiles for me, though i do see the CI error of the differing TSR-types versions on the playout-gateway and blueprints-integration packages. Should this be changed?

**Comment by LindvedKrvang** [comment]
> Compiles for me, though i do see the CI error of the differing TSR-types versions on the playout-gateway and blueprints-integration packages. Should this be changed?

Do you see this just when my PR is checked out or on develop in general?

**Comment by RasmusAlbrektsen** [comment]
> 

I checked your PR out to see, but I see it is the same on develop as well.

**Comment by ianshade** [comment]
@RasmusAlbrektsen there's a task to solve that properly: SOF-1226 😃

**Review by ianshade — APPROVED** [review]

**Pull request merged**
