### PR TITLE
SOF-1280 Now uses AnyEnter for confirm key code

### PR DESCRIPTION
**Pull request by LindvedKrvang**

### CODE REVIEW

**Review by KvelaGorrrrnio — APPROVED** [review]

**Review by ianshade — COMMENTED** [review]
Aren't you creating a conflict with NRK? Why not use core-settings.json?

**Comment by LindvedKrvang** [comment]
> Aren't you creating a conflict with NRK? Why not use core-settings.json?

I didn't give much thought to it...
Is using core-settings.json our preferred way of doing it?
I personnaly lean towards using the defaults, but I think I might be alone on this.
Downside of not doing it in defaults is that we don't have the same functionality enabled by default on our local machines as we have in production

But yes, this would be one of the things that we would with NRK on

**Comment by ianshade** [comment]
> Is using core-settings.json our preferred way of doing it?

You might not prefer it, but it is the only _right_ way for now.

> Downside of not doing it in defaults is that we don't have the same functionality enabled by default on our local machines as we have in production

That needs solving in a smart way, which we've talked about some time ago. Perhaps we could have the json file in our repo, but gitignored by NRK, and loaded only if exists, or perhaps we can move some of these settings to other place that uses configs that can be changed at runtime, similar to Rundown View Layouts

**Comment by LindvedKrvang** [comment]
Also created the PR for changing it in ansible:
https://github.com/tv2/sofie-ansible-prod/pull/14
@ianshade I'm not sure if you can see this. I was unable to select you as a reviewer

**Review by RasmusAlbrektsen — APPROVED** [review]

**Comment by LindvedKrvang** [comment]
> That needs solving in a smart way, which we've talked about some time ago

I think it also comes down to how you view the `DEFAULTS_SETTINGS`. Is it the default for the main fork of Sofie or is it the default for our fork of Sofie?
In mind my it makes sense that you would fork Sofie and then go and alter the values here to fit your needs.
So I view it as our default for Sofie, but maybe we should ask Superfly how they intended `DEFAULTS_SETTINGS` to work?

**Comment by LindvedKrvang** [comment]
Closing the PR due to the change being done in our ansible repos

**Pull request closed without merging**
